### ISSUE TITLE
Deploy fluffi reports OK but has error

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#156] opened 2020-04-21 16:21 UTC
```
PLAY [windows] *****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [batrix3]

TASK [initial-windows-Timezone : Set timezone to 'Romance Standard Time' (GMT+01:00)] ***
ok: [batrix3]

TASK [initial-windows-GFlags : Ensure source directory exists] *****************
ok: [batrix3]

TASK [initial-windows-GFlags : Fetch GFlag zip file "ftp://ftp.fluffi/initial/windows/ansible/GFlags/GFlags.zip"] ***
changed: [batrix3]

TASK [initial-windows-GFlags : Unzip GFlags] ***********************************
changed: [batrix3]

TASK [initial-windows-PrepareEnvironment : Create a FLUFFI directory] **********
ok: [batrix3]

TASK [initial-windows-PrepareEnvironment : Set ACL for C:\FLUFFI] **************
ok: [batrix3]

TASK [initial-windows-PrepareEnvironment : Set AllowUnencrypted to True] *******
fatal: [batrix3]: FAILED! => {"changed": true, "cmd": "Set-Item -Path WSMan:\\localhost\\Service\\AllowUnencrypted -Value $true", "delta": "0:00:03.234031", "end": "2020-04-16 09:33:04.872752", "msg": "non-zero return code", "rc": 1, "start": "2020-04-16 09:33:01.638721", "stderr": "Set-Item : WinRM firewall exception will not work since one of the network connection types on this machine is set to \r\nPublic. Change the network connection type to either Domain or Private and try again. \r\nAt line:1 char:65\r\n+ ... ing $false; Set-Item -Path WSMan:\\localhost\\Service\\AllowUnencrypted  ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [Set-Item], InvalidOperationException\r\n    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.SetItemCommand", "stderr_lines": ["Set-Item : WinRM firewall exception will not work since one of the network connection types on this machine is set to ", "Public. Change the network connection type to either Domain or Private and try again. ", "At line:1 char:65", "+ ... ing $false; Set-Item -Path WSMan:\\localhost\\Service\\AllowUnencrypted  ...", "+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : NotSpecified: (:) [Set-Item], InvalidOperationException", "    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.SetItemCommand"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
batrix3                    : ok=7    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by TomSie** [comment] 2020-04-22 04:28
Duplicate of #154

**Closed as completed** 2020-04-22 04:28 UTC
Labels: duplicate
